name: Release Drafter

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
    - uses: release-drafter/release-drafter@v6
      with:
        disable-releaser: github.ref != 'refs/heads/master'
        config-name: release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
